let items=[
    {
        id: 1,
        image:'images/1.jpg',
        rating: {
            stars: 4.5,
            count: 1400,
        },
        company: 'Carlton London',
        item_name:'Rhodium-Plated CZ Floral Studs',
        current_price: 606,
        orignal_price: 1045,
        discount: 42,
        delivery_time:"10 Oct 2023",
        return_time:14,
    },
    {
        id: 2,
        image:'images/2.jpg',
        rating: {
            stars: 4.3,
            count: 24,
        },
        company: 'CUKOO',
        item_name:'Women Padded Halter Neck Swimming Dress',
        current_price: 1507,
        orignal_price: 2599,
        discount: 42,
        delivery_time:"10 Oct 2023",
        return_time:14,
    },
    {
        id: 3,
        image:'images/3.jpg',
        rating: {
            stars: 4.1,
            count: 249,
        },
        company: 'NUEVOSDAMAS',
        item_name:'Women Red & White Printed A-Line Knee-Length Skirts',
        current_price: 495,
        orignal_price: 1599,
        discount: 69,
        delivery_time:"10 Oct 2023",
        return_time:14,
    },
    {
        id: 4,
        image:'images/4.jpg',
        rating: {
            stars: 5.0,
            count: 10,
        },
        company: 'ADIDAS',
        item_name:'Indian Cricket ODI Jersey',
        current_price: 999,
        orignal_price: 999,
        discount: 0,
        delivery_time:"10 Oct 2023",
        return_time:14,
    },
    {
        id: 5,
        image:'images/5.jpg',
        rating: {
            stars: 4.2,
            count: 3500,
        },
        company: 'Roadster',
        item_name:'Pure Cotton T-shirt',
        current_price: 495,
        orignal_price: 1599,
        discount: 69,
        delivery_time:"10 Oct 2023",
        return_time:14,
    },
    {
        id: 6,
        image:'images/6.jpg',
        rating: {
            stars: 0.0,
            count: 0,
        },
        company: 'Nike',
        item_name:'Men ReactX Running Shoes',
        current_price: 14995,
        orignal_price: 14995,
        discount: 0,
        delivery_time:"10 Oct 2023",
        return_time:14,
    },
    {
        id: 7,
        image:'images/7.jpg',
        rating: {
            stars: 4.2,
            count: 388,
        },
        company: 'The Indian Garage Co',
        item_name:'Men Slim Fit Regular Shorts',
        current_price: 639,
        orignal_price: 1599,
        discount: 60,
        delivery_time:"10 Oct 2023",
        return_time:14,
    },
    {
        id: 8,
        image:'images/8.jpg',
        rating: {
            stars: 4.2,
            count: 5200,
        },
        company: 'Nivea',
        item_name:'Men Fresh Deodrant 150ml',
        current_price: 142,
        orignal_price: 285,
        discount: 50,
        delivery_time:"10 Oct 2023",
        return_time:14,
    },
]